name: Build and Create Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

      - name: Package Code
        run: zip -r calculator_artifact.zip src/ requirements.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: calculator
          path: calculator_artifact.zip
