name: Build and Create Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_artifacts:
        description: 'Build Artifacts (true/false)'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_artifacts == 'true' || github.event_name == 'push' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # Create a requirements.txt dynamically (optional, if dependencies are added)
        run: |
          echo "pytest" > requirements.txt
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          # Add tests here if applicable, or remove this step if no tests exist
          echo "No tests available yet."

      - name: Package Code
        # Archive cal.py and any other necessary files
        run: zip -r calculator_artifact.zip cal.py requirements.txt README.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator
          path: calculator_artifact.zip
