name: Build and Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          echo "pytest" > requirements.txt
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "No tests available yet."

      - name: Package Code
        run: |
          zip -r calculator_artifact.zip cal.py requirements.txt README.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator
          path: calculator_artifact.zip

  publish_to_pypi:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Build Tools
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build Distribution Files
        run: python setup.py sdist bdist_wheel

      - name: List Dist Directory
        run: ls -l dist

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: python -m twine upload dist/*
