name: Build and Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          echo "pytest" > requirements.txt
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          echo "No tests available yet."

      # Step 5: Package Code
      - name: Package Code
        run: |
          zip -r calculator_artifact.zip cal.py requirements.txt README.md

      # Step 6: Upload Artifact (Optional)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator
          path: calculator_artifact.zip

      # Step 7: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      # Step 8: Upload Artifact to AWS CodeArtifact
      - name: Upload to AWS CodeArtifact
        run: |
          aws codeartifact put-package-asset \
            --domain jill \
            --domain-owner 897729129103 \
            --repository AK \
            --package calculator \
            --package-version 1.0.0 \
            --asset calculator_artifact.zip \
            --asset-name calculator_artifact.zip
