name: Build and Publish Python Package to AWS CodeArtifact

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger this workflow

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        echo "pytest" > requirements.txt
        pip install -r requirements.txt

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        echo "No tests available yet."

    # Step 5: Build the Python Package
    - name: Build Python Package
      run: |
        python setup.py sdist bdist_wheel

    # Step 6: Configure AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    # Step 7: Login to AWS CodeArtifact
    - name: Login to AWS CodeArtifact
      run: |
        aws codeartifact login \
          --tool twine \
          --repository AK \
          --domain jill \
          --domain-owner <account-id>  # Replace with your AWS account ID

    # Step 8: Publish Python Package to AWS CodeArtifact
    - name: Publish Package
      run: |
        twine upload --repository codeartifact dist/*

    # Optional: Upload the Artifact to GitHub (For Backup or Debugging)
    - name: Upload Package Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: calculator-package
        path: dist/*
