name: Build and Publish Python Package to AWS CodeArtifact

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install setuptools wheel twine setuptools-scm

      # Step 4: Configure Git User
      - name: Configure Git User
        run: |
          git config user.name "akhilesh"
          git config user.email "akhileshmony@gmail.com"

      # Step 5: Bump Version (Patch)
      - name: Bump Version (Patch)
        id: bump_version
        run: |
          set -e  # Exit on error
          # Get the current version or fallback to V1.0.0
          CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "V1.0.0")
          echo "Current Version: $CURRENT_VERSION"
          # Strip the 'V' prefix for version manipulation
          BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/^V//')
          echo "Base Version (without V): $BASE_VERSION"
          # Increment the patch version
          NEW_VERSION=$(python -c "v='$BASE_VERSION'; parts=v.split('.'); parts[-1]=str(int(parts[-1])+1); print('V' + '.'.join(parts))")
          echo "New Version: $NEW_VERSION"
          # Validate the new version
          if [ -z "$NEW_VERSION" ]; then
            echo "Error: NEW_VERSION is empty."
            exit 1
          fi
          # Set new version as an environment variable and workflow output
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=new_version::$NEW_VERSION"
          # Tag the new version
          git tag "$NEW_VERSION"

      # Step 6: Check if Version Exists in CodeArtifact
      - name: Check Version in AWS CodeArtifact
        id: check_version
        run: |
          VERSION_EXISTS=$(aws codeartifact list-packages --domain ak --domain-owner 897729129103 --repository pypi-store --package calculator --query "packages[?version=='${{ steps.bump_version.outputs.new_version }}'].version" --output text)
          echo "Version Exists: $VERSION_EXISTS"
          if [ "$VERSION_EXISTS" != "None" ]; then
            echo "Version ${{ steps.bump_version.outputs.new_version }} already exists, bumping version..."
            # Increment the version if it exists
            BASE_VERSION=$(echo "${{ steps.bump_version.outputs.new_version }}" | sed 's/^V//')
            NEW_VERSION=$(python -c "v='$BASE_VERSION'; parts=v.split('.'); parts[-1]=str(int(parts[-1])+1); print('V' + '.'.join(parts))")
            echo "New Version after bump: $NEW_VERSION"
            echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
            echo "::set-output name=new_version::$NEW_VERSION"
            git tag "$NEW_VERSION"
          fi

      # Step 7: Push New Tag
      - name: Push New Tag
        env:
          PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          set -e  # Exit on error
          echo "Pushing New Tag: ${{ steps.check_version.outputs.new_version }}"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push origin "${{ steps.check_version.outputs.new_version }}"

      # Step 8: Build Python Package
      - name: Build Python Package
        run: |
          python setup.py sdist bdist_wheel

      # Step 9: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 10: Login to AWS CodeArtifact
      - name: Login to AWS CodeArtifact
        run: |
          aws codeartifact login \
            --tool twine \
            --repository pypi-store \
            --domain ak \
            --domain-owner 897729129103

      # Step 11: Publish Package
      - name: Publish Package
        run: |
          twine upload --repository codeartifact --verbose dist/*

      # Step 12: Upload Package Artifact to GitHub
      - name: Upload Package Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: calculator-package
          path: dist/*
